// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-0cSOcSxkQe7Wmc4a-Ueyh5KFY237o4',
    appId: '1:805169235853:web:8e4e44f2b04661948b9fc4',
    messagingSenderId: '805169235853',
    projectId: 'expense-tracker-e4de5',
    authDomain: 'expense-tracker-e4de5.firebaseapp.com',
    storageBucket: 'expense-tracker-e4de5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRFVJDzfcVVVxfmqVVczu8IRYMPa9ipIk',
    appId: '1:805169235853:android:7b9803067986a87f8b9fc4',
    messagingSenderId: '805169235853',
    projectId: 'expense-tracker-e4de5',
    storageBucket: 'expense-tracker-e4de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRBmkQySJl3efP0BEDT31n5MnmcbkMX0',
    appId: '1:805169235853:ios:6ab193f45398698b8b9fc4',
    messagingSenderId: '805169235853',
    projectId: 'expense-tracker-e4de5',
    storageBucket: 'expense-tracker-e4de5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnRBmkQySJl3efP0BEDT31n5MnmcbkMX0',
    appId: '1:805169235853:ios:6ab193f45398698b8b9fc4',
    messagingSenderId: '805169235853',
    projectId: 'expense-tracker-e4de5',
    storageBucket: 'expense-tracker-e4de5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL-0cSOcSxkQe7Wmc4a-Ueyh5KFY237o4',
    appId: '1:805169235853:web:76648779500ffdb58b9fc4',
    messagingSenderId: '805169235853',
    projectId: 'expense-tracker-e4de5',
    authDomain: 'expense-tracker-e4de5.firebaseapp.com',
    storageBucket: 'expense-tracker-e4de5.firebasestorage.app',
  );
}
